genes:
  - COI
  - CYTB
  - ITS2

data_dir: "data"

alignment:
  mafft_method: "--auto"        # MAFFT alignment strategy
  trimal_method: "-automated1"  # trimAl trimming method

phylogeny:
  bootstrap: 100   # standard bootstrap replicates (-b); produces .contree

threads:
  mafft:   4
  trimal:  1
  iqtree:  8
  astral:  4
